SELECT P.ID
	  ,SUM( DATEDIFF( 'MONTH', P.START_DATE, P.FINISH_DATE ) * W.SALARY ) AS PROJECT_PRICE
FROM   PROJECT P
JOIN   PROJECT_WORKER PW
    ON PW.PROJECT_ID = P.ID
JOIN   WORKER W
    ON W.ID = PW.WORKER_ID
GROUP BY P.ID